import React from "react";
import AppProvider from "@/src";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Code Challenge",
  description: "Generated by create next app",
  robots: "noindex"
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppProvider>
          {children}
        </AppProvider>
        <Toaster position="bottom-left" />
      </body>
    </html>
  );
}
